name: Self-Hosted Runner Build

on:
  push:
    branches: [staging1]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted # or [self-hosted, label1] to pick a runner by label
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Node.js version to install
          cache: 'npm' # caches npm packages for faster runs

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
